repos:
  - repo: local
    hooks:
      - id: repo-format
        name: format frontend+backend
        entry: bash -lc 'make format'
        language: system
        pass_filenames: false

      - id: repo-lint
        name: lint frontend+backend
        entry: bash -lc 'make lint'
        language: system
        pass_filenames: false
